  FindDeals::Cities.create(name: "sydney")
  FindDeals::Cities.create(name: "melbourne")
  FindDeals::Cities.create(name: "perth")
  FindDeals::Cities.create(name: "brisbane")
  FindDeals::Cities.create(name: "adelaide")
  FindDeals::Cities.create(name: "gold-coast")

  FindDeals::Categories.create(name: nil)
  FindDeals::Categories.create(name: "dining")
  FindDeals::Categories.create(name: "wellness-beauty")
  FindDeals::Categories.create(name: "activities")
  FindDeals::Categories.create(name: "shopping")
  FindDeals::Categories.create(name: "services")
  FindDeals::Categories.create(name: "wine")
  FindDeals::Categories.create(name: "personalised-gifts")