  Cities.find_or_create_by(name: "sydney")
  Cities.find_or_create_by(name: "melbourne")
  Cities.find_or_create_by(name: "perth")
  Cities.find_or_create_by(name: "brisbane")
  Cities.find_or_create_by(name: "adelaide")
  Cities.find_or_create_by(name: "gold-coast")

  Categories.find_or_create_by(name: nil)
  Categories.find_or_create_by(name: "dining")
  Categories.find_or_create_by(name: "wellness-beauty")
  Categories.find_or_create_by(name: "activities")
  Categories.find_or_create_by(name: "shopping")
  Categories.find_or_create_by(name: "services")
  Categories.find_or_create_by(name: "wine")
  Categories.find_or_create_by(name: "personalised-gifts")